name: fiber_fit_env
channels:
  - conda-forge
  - astra-toolbox
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astra-toolbox=2.1.2
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - cloudpickle=2.0.0
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2022.7.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - flit-core=3.8.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2023.3.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5grove=1.3.0
  - h5py=3.7.0
  - hdf5=1.10.6
  - hdf5plugin=3.2.0
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.26.0
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.10.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_console=6.6.2
  - jupyter_core=5.2.0
  - jupyter_events=0.6.3
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.19.0
  - jupyterlab_widgets=3.0.5
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libastra=2.1.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcurl=7.88.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libnghttp2=1.46.0
  - libpng=1.6.39
  - libpq=12.9
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzopfli=1.0.3
  - locket=1.0.0
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclassic=0.5.2
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - nodejs=12.4.0
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=2.5.2
  - ply=3.11
  - pooch=1.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python_abi=3.9
  - pytz=2022.7
  - pywavelets=1.4.1
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.0
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scikit-image=0.19.3
  - scipy=1.10.0
  - send2trash=1.8.0
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.1
  - stack_data=0.2.0
  - terminado=0.17.1
  - tifffile=2021.7.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomopy=1.11.0
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - xz=5.2.10
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - anyio==3.7.1
      - astropy==5.3.4
      - basemap==1.4.1
      - basemap-data==1.3.2
      - cbf==1.2.0
      - colorcet==3.0.1
      - colorspacious==1.1.2
      - connected-components-3d==3.16.0
      - diplib==3.5.1
      - et-xmlfile==1.1.0
      - fabio==2022.12.1
      - fisx==1.3.1
      - ipympl==0.9.3
      - itk-core==5.4.0
      - itk-io==5.4.0
      - itk-ioscanco==0.10.0
      - joblib==1.3.2
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-resource-usage==0.7.2
      - jupyter-server==1.24.0
      - jupyterlab-h5web==8.0.0
      - llvmlite==0.39.1
      - mako==1.2.4
      - numba==0.56.3
      - numpy==1.23.5
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.8.1.78
      - openpyxl==3.1.2
      - orjson==3.9.5
      - packaging==23.2
      - pandas==2.1.2
      - param==1.13.0
      - patchify==0.2.3
      - patsy==1.0.1
      - pyct==0.5.0
      - pyerfa==2.0.1.1
      - pymca==5.9.1
      - pymca5==5.9.1
      - pyopencl==2023.1.2
      - pyopengl==3.1.7
      - pyproj==3.6.1
      - pyqt5==5.15.5
      - pyqt5-qt5==5.15.2
      - pyshp==2.3.1
      - pyside2==5.15.2.1
      - pyside6==6.2.4
      - pytools==2023.1.1
      - pyzmq==26.2.0
      - rampy==0.4.9
      - scikit-learn==1.3.2
      - seaborn==0.13.2
      - shiboken2==5.15.2.1
      - shiboken6==6.2.4
      - silx==1.1.2
      - simpleitk==2.3.1
      - statsmodels==0.14.4
      - tabulate==0.9.0
      - threadpoolctl==3.2.0
      - tzdata==2023.3
      - vtk==9.5.2
      - wget==3.2
      - xarray==2023.10.1
      - xcffib==1.5.0
      - xlrd==2.0.1
      - lovely_tensors
